name: Move from In Progress to Review

on:
  issues:
    types:
      - assigned
jobs:
  move-assigned-card:
    runs-on: ubuntu-latest
    steps:
      - uses: 
        with:
          project: CAP Board
          column: Review
          repo-token:
